postgres:
  ARTIFACT_DESCRIPTOR_VERSION: 16.4-oss-1
  CPU_LIMIT: '1'
  CPU_REQUEST: 100m
  DEPLOYMENT_RESOURCE_NAME: postgres-v1
  DEPLOYMENT_VERSION: v1
  DOCKER_TAG: docker.io/library/postgres:16-alpine
  IMAGE_REPOSITORY: docker.io/library/postgres
  MEMORY_LIMIT: 1Gi
  MEMORY_REQUEST: 256Mi
  SERVICE_NAME: postgres
  TAG: 16-alpine
