API_DBAAS_ADDRESS: http://dbaas.dbaas:8888
BUILD_TAG_NEW: keycloak-database
CLOUDNAME: test-env
CLOUD_API_HOST: temp.cloud.com
CLOUD_API_PORT: '1111'
CLOUD_DASHBOARD_URL: https://dashboard.test-env.managed.temp.cloud
CLOUD_PRIVATE_HOST: test-env.managed.temp.cloud
CLOUD_PROTOCOL: https
CLOUD_PUBLIC_HOST: test-env.managed.temp.cloud
CMDB_URL: https://test-env.managed.temp.cloud
CUSTOM_HOST: test-env.managed.temp.cloud
DBAAS_AGGREGATOR_ADDRESS: https://dbaas.None
DBAAS_AGGREGATOR_PASSWORD: test-dbaas-pass
DBAAS_AGGREGATOR_USERNAME: test-dbaas-user
DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD: test-dbaas-pass
DBAAS_CLUSTER_DBA_CREDENTIALS_USERNAME: test-dbaas-user
DBAAS_ENABLED: false
ENVGENE_CONFIG_REF_NAME: feat/check_updates
ENVGENE_CONFIG_TAG: No Ref tag
ENV_NAME: e03
GATEWAY_URL: http://internal-gateway-service:8080
GRAFANA_UI_URL: https://test-env.managed.temp.cloud
GRAYLOG_UI_URL: https://test-env.managed.temp.cloud
MAAS_ENABLED: false
NAMESPACE: e03-pg
OPENSHIFT_SERVER: https://temp.cloud.com:1111
ORIGIN_NAMESPACE: e03-pg
PG_NAMESPACE_FROM_SD: e03-pg
PG_VERSION_FROM_SD: 16.4-oss-1
POSTGRES_DBA_PASSWORD: test
POSTGRES_DBA_USER: test
PRIVATE_GATEWAY_URL: https://private-gateway-e03-pg.test-env.managed.temp.cloud
PRIVATE_IDENTITY_PROVIDER_URL: https://private-gateway-e03-pg.test-env.managed.temp.cloud
PRODUCTION_MODE: false
PUBLIC_GATEWAY_URL: https://public-gateway-e03-pg.test-env.managed.temp.cloud
PUBLIC_IDENTITY_PROVIDER_URL: https://public-gateway-e03-pg.test-env.managed.temp.cloud
SERVER_HOSTNAME: test-env.managed.temp.cloud
STATIC_CACHE_SERVICE_ROUTE_HOST: static-cache-service-e03-pg.test-env.managed.temp.cloud
TBAPI_URL: http://test
TENANTNAME: test-tenant
TRACING_UI_URL: https://test-env.managed.temp.cloud
VALUE: 'true'
key1: value2
