---

# ENV_INVENTORY_INIT: false
# GENERATE_EFFECTIVE_SET: false
# ENV_TEMPLATE_TEST: false
# ENV_TEMPLATE_NAME: ''
# SD_DATA: '{}'
# SD_VERSION: ''
# SD_SOURCE_TYPE: ''
# SD_DELTA: false
# ENV_SPECIFIC_PARAMETERS: {}
# CRED_ROTATION_PAYLOAD: |
#   {
#     "rotation_items": [
#       {
#         "namespace": "e02-bss",
#         "application": "postgres",
#         "context": "deployment",
#         "parameter_key": "POSTGRES_DBA_USER",
#         "parameter_value": "new_postgres_user"
#       },
#       {
#         "namespace": "e02-bss",
#         "application": "postgres",
#         "context": "deployment",
#         "parameter_key": "POSTGRES_DBA_PASSWORD",
#         "parameter_value": "new_postgres_password"
#       },
#       {
#         "namespace": "e02-core",
#         "application": "postgres-service",
#         "context": "deployment",
#         "parameter_key": "POSTGRES_DBA_USER",
#         "parameter_value": "new_core_user"
#       },
#       {
#         "namespace": "e02-core",
#         "application": "postgres-service",
#         "context": "deployment",
#         "parameter_key": "POSTGRES_DBA_PASSWORD",
#         "parameter_value": "new_core_password"
#       }
#     ]
#   }
# CRED_ROTATION_FORCE: true
