---

# Pipeline Configuration  
DEPLOYMENT_TICKET_ID: 'TEST-TICKET-1'
ENV_NAMES: 'test-cluster/e02'
ENV_INVENTORY_INIT: false
ENV_BUILDER: true
GENERATE_EFFECTIVE_SET: false
CMDB_IMPORT: false
GET_PASSPORT: false
ENV_TEMPLATE_VERSION: ''

# Existing Variables
ENV_TEMPLATE_TEST: false #boolean - only true or false
ENV_TEMPLATE_NAME: ''
SD_DATA: '{}'
SD_VERSION: ''
SD_SOURCE_TYPE: ''
SD_DELTA: false
ENV_SPECIFIC_PARAMETERS: {}