---

# Variables that are read from file (not manually input)
ENV_INVENTORY_INIT: false
GENERATE_EFFECTIVE_SET: false
ENV_TEMPLATE_TEST: false
ENV_TEMPLATE_NAME: ''
SD_DATA: '{}'
SD_VERSION: ''
SD_SOURCE_TYPE: ''
SD_DELTA: false
ENV_SPECIFIC_PARAMETERS: {}