name: "Download artifact"
description: "Get artifact id, download it and unzip to required directory"
author: "Qubership"

inputs:
  sanitized_name:
    description: "Updated environment name without special symbols."
    required: true
    type: string
  full_env:
    description: "Full environment name."
    required: true
    type: string
  project_dir:
    description: "Workspace."
    required: true
    type: string

outputs:
  artifact_id:
    description: "The ID of the matched artifact"
    value: ${{ steps.get-artifact.outputs.artifact_id }}

runs:
  using: "composite"
  steps:
    - name: Download artifact using standard GitHub action
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.sanitized_name }}
        path: ./downloaded_artifact

    - name: Extract and copy artifact contents
      shell: bash
      run: |
        echo "=== Downloaded artifact contents ==="
        ls -la ./downloaded_artifact
        
        # Find the environment directory in downloaded artifact
        ENV_DIR="./downloaded_artifact/${{ inputs.full_env }}"
        if [ -d "$ENV_DIR" ]; then
          echo "Found environment directory: $ENV_DIR"
          
          # Ensure destination directory exists
          mkdir -p "${{ inputs.project_dir }}/environments/${{ inputs.full_env }}/"
          
          echo "Copying files to destination..."
          echo "Source: $ENV_DIR"
          echo "Destination: ${{ inputs.project_dir }}/environments/${{ inputs.full_env }}/"
          
          # Copy files recursively, overwriting existing ones
          cp -rf "$ENV_DIR"/* "${{ inputs.project_dir }}/environments/${{ inputs.full_env }}/"
          echo "Files copied successfully"
          
          # Show what was copied
          echo "=== Copied files preview ==="
          find "${{ inputs.project_dir }}/environments/${{ inputs.full_env }}" -name "*.yml" -o -name "*.yaml" | head -3 | while read file; do
            echo "File: $file"
            echo "Content preview:"
            head -n 5 "$file" || echo "Cannot read file"
            echo "---"
          done
          
        else
          echo "ERROR: Environment directory '${{ inputs.full_env }}' not found in artifact"
          echo "Available contents:"
          find ./downloaded_artifact -type d
          
          # Try to find any matching directory pattern
          echo "Looking for any pattern containing environment name..."
          find ./downloaded_artifact -name "*e02*" -o -name "*test-cluster*" || echo "No matching patterns found"
        fi
        
        # Clean up
        rm -rf ./downloaded_artifact