#Enchanced version to create EnvGene, based on github best practices
name: "Generate Envgene"
run-name: "Generate Envgene - ${{ github.event.inputs.ENV_NAMES }}"
permissions:
  actions: read
  contents: write
  pull-requests: write
on:
  push:
  workflow_dispatch:
    inputs:
      ENV_NAMES:
        required: false
        type: string
        description: ""
      ENV_TEMPLATE_VERSION:
        required: false
        default: ""
        type: string
        description: ""
      ENV_BUILDER:
        required: false
        default: "true"
        type: string
        description: ""
jobs:
  checkout_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  first_job:
    runs-on: ubuntu-latest
    needs: checkout_repo
    steps:
      - name: Use code from repository
        run: |
          echo "Code from repository is available here!"
          ls -l $GITHUB_WORKSPACE
